[package]
name = "rose-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
homepage.workspace = true

[[bin]]
name = "rose"
path = "src/main.rs"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ target }-v{ version }{ archive-suffix }"
bin-dir = "{ name }-{ target }-v{ version }/{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
rose = { version = "0.1.0", path = "../lib" }
tokio.workspace = true

[build-dependencies]
clap = { version = "4.5.60", features = ["derive"] }
clap_mangen = "0.2.31"
