//! Configuration and certificate management.
//!
//! Manages paths for certificates, known hosts, and authorized certs:
//! - `~/.config/rose/authorized_certs/` — client certs authorized to connect (server side)
//! - `~/.config/rose/known_hosts/` — TOFU server cert cache (client side)
//! - Client and server X.509 certificates generated by `rose keygen`
